-- AlterTable
ALTER TABLE "Users" ALTER COLUMN "last_login" DROP NOT NULL,
ALTER COLUMN "last_login" SET DATA TYPE TIMESTAMP(0),
ALTER COLUMN "updated_at" DROP NOT NULL,
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMP(0);
