-- AlterTable
ALTER TABLE "Users" ALTER COLUMN "middle_name" DROP NOT NULL,
ALTER COLUMN "status" SET DEFAULT '1',
ALTER COLUMN "sex" DROP NOT NULL,
ALTER COLUMN "barangay" DROP NOT NULL,
ALTER COLUMN "city_municipal" DROP NOT NULL,
ALTER COLUMN "postal_code" DROP NOT NULL,
ALTER COLUMN "country" DROP NOT NULL,
ALTER COLUMN "province" DROP NOT NULL,
ALTER COLUMN "role_Id" DROP NOT NULL;
